import {Puzzle, PuzzleMetadata} from './binaryEncoder';

const normalPuzzle: PuzzleMetadata = {'extensionsOrder': [],
	'author': 'Aimee Lucido / Will Shortz',
	'clues': ['Destination for NASA\'s Perseverance rover',
		'Counterparts of sirs',
		'Full of love',
		'"50 First Dates" and "27 Dresses," for two',
		'Enjoy the slopes',
		'Rolls up, as pant legs',
		'Sonny Corleone portrayer in "The Godfather"',
		'Sport played with a Frisbee',
		'Physicist Enrico',
		'Certain status on social media',
		'"Red" or "White" team',
		'Singer/actress Lady ___',
		'Tropical fruit often found in smoothies',
		'Regarded with respect',
		'"At least you did your best!"',
		'Ques. counterpart',
		'In a wild way',
		'Final Oldsmobile model',
		'Thick noodles in Japanese soups',
		'Woman who might wield a whip',
		'Tammany Hall caricaturist Thomas',
		'"Famous" cookie guy',
		'Shape of this answer\'s third letter',
		'Art form from Japan',
		'Fanatical',
		'At full speed, nautically',
		'Pioneering synthesizers introduced in the 1960s',
		'Weed',
		'Gas station conveniences',
		'Completely',
		'"Get it?"',
		'Eastern island on the Equator',
		'Stick around',
		'Stuff spliced in a lab',
		'Poetry palindrome',
		'I.R.S. identifier, for short',
		'Greek "H"',
		'Result of burnout?',
		'Decorate colorfully, in a way',
		'Famous Ford flop',
		'Character associated with the beverage "shaken" in this puzzle\'s circled letters',
		'Titular woman in a #1 Rolling Stones hit',
		'They might be full of beans',
		'Shelter by the beach',
		'Recording device, informally',
		'Slightly better',
		'Mozzarella-and-cream cheese often served as an appetizer',
		'Simple shelter',
		'Name that\'s also a major Australian airport code',
		'Posing surface',
		'First female singer to have multiple albums exceed 10 billion streams on Spotify',
		'Tempe sch.',
		'Meme that moves, maybe',
		'Opera\'s "barber of Seville"',
		'Weathered, as a storm',
		'"I don\'t give a ___!"',
		'Preview',
		'Tallest peak in the Cascades',
		'Birch relative',
		'Mistake',
		'Pond buildup',
		'___ Stanley Gardner, creator of Perry Mason',
		'Last name of two brotherly fairy tale writers',
		'Tiny arachnid',
		'In the style of',
		'Modern checkout device in lieu of a cashier',
		'Sends a ping, in brief',
		'British author known for his 1984 novel "Money"',
		'Studio with a lion mascot',
		'Symbols for tagging on Twitter',
		'Zoom button you might click when your dog barks',
		'Treelike member of Marvel\'s Guardians of the Galaxy',
		'Record, in a way',
		'Practice boxing',
		'Man with a code',
		'Common flag symbol'],
	'copyright': '© 2023, The New York Times',
	'encoding': 'binary',
	'extensions': {},
	'fileversion': Buffer.from('1.3', 'binary'),
	'fill': '----.-----.--------.-----.--------------.-------.-----.----.-----.----------------.---.---.---.---.------...---------...------.---.---.---.---.----------------.-----.----.-----.-------.--------------.-----.--------.-----.----',
	'height': 15,
	'helpers': {},
	'notes': '',
	'postscript': Buffer.from(''),
	'preamble': Buffer.from(''),
	'puzzleType': 1,
	'scrambledCksum': 0,
	'solution': 'MARS.CUFFS.GAGAAMOK.ALERO.UDONDOMINATRIX.AMOSARC.ANIME.AVID.MOOGS.MINIMARTSSUMATRA.DNA.ERE.SSN.ETA.TIEDYE...JAMESBOND...CABANA.HUT.SYD.ASU.GIF.RODEOUTMTRAINIER.ALGAE.ERLE.GRIMM.ALAIPAD.MARTINAMISMUTE.GROOT.TAPESPAR.MORSE.STAR',
	'solutionState': 0,
	'title': 'NY Times, Tuesday, May 2, 2023',
	'unk1': Buffer.alloc(2),
	'unk2': Buffer.alloc(12),
	'version': Buffer.from('1.3', 'binary'),
	'width': 15};


export function getBuf(): Buffer{
	const puzzle = new Puzzle(normalPuzzle);
	return puzzle.toBuffer();
}

